spring:
  datasource:
    url: jdbc:mysql://101.132.155.127:3306/camunda2?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: jlm200065

camunda:
  bpm:
    admin-user:
      id: admin
      password: 123456
#    auto-deployment-enabled: true
#    history-level: audit
